<a href="https://colab.research.google.com/github/Nimmi8757/Basic_Command/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Advantage of numpy arrays are:
1.Allows several mthematical operations
2.faster operation

In [ ]:
import numpy as np
from time import process_time

In [ ]:
python_list=[i for i in range(10000)]
start_time= process_time()
python_list =[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)


0.0010768350000001092


In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.00023343100000161598


Numpy arrays

In [ ]:
#lists
list1=[1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [ ]:
np_array=np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

In [ ]:
# array of particular value
z=np.full((5,4),0)

In [ ]:
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
# identity matrix
a=np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


# New section